version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql-banco-container
    restart: always
    environment:
      MYSQL_DATABASE: banco_db
      MYSQL_ROOT_PASSWORD: "154413711"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: